using Day8;
using AdventTests;
using AdventUtils;

namespace AdventTests
{
    [TestClass]
    public sealed class Day8Tests
    {
        public static readonly string testGrid = @"
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
        ".Trim();
        private static readonly CharGrid grid = new(testGrid.Split(Environment.NewLine).ToList());
        private static readonly AntinodeLocator locator = new(grid);

        [TestMethod]
        public void TestAntinodes()
        {
            Assert.AreEqual(14, locator.NumAntinodes());
            Assert.AreEqual(34, locator.NumCollinear());
        }
    }
}
